"""Add batch_size column to equipment table

Revision ID: 56277a4bac8f
Revises: 
Create Date: 2026-01-06 19:09:13.758725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56277a4bac8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_size', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_column('batch_size')

    # ### end Alembic commands ###
